version: "3.8"

services:
  backend: 
    depends_on: 
      - db
    build: ./
    ports: 
      - 3000:3000
    volumes:
      - ./:/app
    environment: 
      DB_URL: mongodb://db/damageTrack
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - damageTrack:/data/db

volumes:
  damageTrack:
